### PR TITLE
[JENKINS-65161] remove commons-digester2 from core and upgrade plugins to commons-digester3

### PR DESCRIPTION
**Pull request by olamy**

### CODE REVIEW

**Comment by olamy** [comment]
https://github.com/jenkinsci/jenkins/pull/5320

**Comment by batmat** [comment]
Hi @mrmoritz01, thanks a lot for merging this PR :). 
Would you be able to consider releasing this?

Thanks again!

**Comment by basil** [comment]
Does this not introduce a security vulnerability? I don't see the XXE mitigations in this PR that I see in the other similar PRs.

**Comment by basil** [comment]
Phew, sorry for the false alarm.

**Comment by batmat** [comment]
Better safe than sorry, thanks for cross-checking Basil!

**Comment by mrmoritz01** [comment]
@batmat This is released in cvs-plugin 2.19 now.

**Pull request merged**
