### PR TITLE
Fix NullPointerException in CVSRepository.

### PR DESCRIPTION
**Pull request by davidpelfree**
Resolves: JENKINS-54525, JENKINS-54656.

### CODE REVIEW

**Comment by davidpelfree** [comment]
@jglick  are you OK with this fix?

**Comment by jglick** [comment]
I do not maintain this plugin. I have no idea if anyone does.

**Comment by mrmoritz01** [comment]
Please also have a look at #49 - it resolves the source of the nullpointer handled in your fix.

**Comment by DanielO** [comment]
Works For Me (tm)

**Comment by andrewducker** [comment]
Last person who merged was @mc1arke - it's possible he still occasionally maintains it.
Michael, are you willing to pick this up?

**Comment by mc1arke** [comment]
I no longer use CVS so can't really test these changes. I'm happy to merge a fix (#49 would probably be a better fix than this one) and attempt a release, but ideally we need someone who uses the plugin to take ownership of the plugin.

**Comment by andrewducker** [comment]
Really appreciated.
(And agreed on both points)

**Comment by sudarshan-ctl** [comment]
hi. Is it possible to commit this plugin. We are blocked with a migration project and would love to have this plugin in our corporate Jenkins tool

**Comment by jglick** [comment]
https://jenkins.io/doc/developer/plugin-governance/adopt-a-plugin/

**Comment by mrmoritz01** [comment]
https://groups.google.com/forum/#!topic/jenkinsci-dev/rPr6eNVphY4

**Comment by mrmoritz01** [comment]
CVS Plugin 2.15 is now released, which fixes the Excluded Regions-Bug.

**Comment by mrmoritz01** [comment]
Since this is fixed in 2.15 release, this PR can now be closed.

**Pull request closed without merging**
