### PR TITLE
[FIXED JENKINS-26345] "CVS Symbolic Name parameter" not working any more

### PR DESCRIPTION
**Pull request by fredg02**
This fix is inspired by this commit: https://github.com/kohsuke/Hudson-GIT-plugin/commit/f92bb2fd650545e740f409824a6ca27fca34c70a

Please let me know if it can be improved.

### CODE REVIEW

**Comment by tmcoma** [comment]
Have you gotten any response on this?  If not, it might be worth it to sign the agreements for commit access and try to get it in.

**Comment by fredg02** [comment]
@kohsuke or @jglick: Is it OK If I merge this PR? It has been running in production for 10 months successfully.

**Comment by fredg02** [comment]
It's been a week without a reply. Since this is basically a copy-and-paste of a fix that @kohsuke did and it's battle tested in production I consider the risk to be quite low. Therefore I'm merging this.

**Comment by jglick** [comment]
@mc1arke FYI

**Pull request merged**
