### PR TITLE
JENKINS-64535 Improve compatibility with Jenkins >2.263

### PR DESCRIPTION
**Pull request by timja**
See https://issues.jenkins.io/browse/JENKINS-64341

and 

https://www.jenkins.io/doc/developer/views/table-to-div-migration/

@mrmoritz01

### CODE REVIEW

**Review by oleg-nenashev — APPROVED** [review]
OK? Not sure this plugin is still used though

**Comment by timja** [comment]
may not be used but it's still installed by some people, I tried to fix as many of those as possible

**Comment by mrmoritz01** [comment]
> 
> 
> OK? Not sure this plugin is still used though

There are still some people left, that need to use CVS for whatever reason. So let's get this fixed.

Do you have any hint why the continuous-integration/jenkins/pr-merge and Jenkins-Jobs fail because of missing JUnit Test Reports?

**Comment by mrmoritz01** [comment]
continuous-integration/jenkins/pr-merge — This commit cannot be built:



[2020-12-29T15:48:50.985Z] EC2 (aws) - High memory ubuntu 18.04  (i-0816c75dbc1897214) was marked offline: Connection was broken: java.io.EOFException

[2020-12-29T15:48:50.985Z] 	at java.base/java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2872)

[2020-12-29T15:48:50.985Z] 	at java.base/java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3367)

[2020-12-29T15:48:50.985Z] 	at java.base/java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:936)

[2020-12-29T15:48:50.985Z] 	at java.base/java.io.ObjectInputStream.<init>(ObjectInputStream.java:379)

[2020-12-29T15:48:50.985Z] 	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:49)

[2020-12-29T15:48:50.985Z] 	at hudson.remoting.Command.readFrom(Command.java:142)

[2020-12-29T15:48:50.985Z] 	at hudson.remoting.Command.readFrom(Command.java:128)

[2020-12-29T15:48:50.985Z] 	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:35)

[2020-12-29T15:48:50.985Z] 	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:63)

[2020-12-29T15:48:50.985Z] Caused: java.io.IOException: Unexpected termination of the channel

[2020-12-29T15:48:50.985Z] 	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:77)


Any idea on that?

**Comment by timja** [comment]
> > OK? Not sure this plugin is still used though
> 
> There are still some people left, that need to use CVS for whatever reason. So let's get this fixed.
> 
> Do you have any hint why the continuous-integration/jenkins/pr-merge and Jenkins-Jobs fail because of missing JUnit Test Reports?

Yes it's fixed in https://github.com/jenkinsci/cvs-plugin/pull/53

It's not actually failing due to missing junit reports, one of the other branches has failed.

**Comment by fqueiruga** [comment]
May I ask if there's an approximate release date for this fix?

**Comment by mrmoritz01** [comment]
@fqueiruga cvs-plugin 2.18 is released
https://plugins.jenkins.io/cvs/#releases

**Pull request merged**
