### PR TITLE
what does this plugin do?

### PR DESCRIPTION
**Pull request by IRobL**
Hi, I just flowed in from the [wiki](https://wiki.jenkins-ci.org/display/JENKINS/Job+Import+Plugin), and while documentation does exist, it's still unclear what this plugin does.  Could someone please discuss here or fill in a few tidbits into the readme of this PR?

Thanks!

### CODE REVIEW

**Comment by mc1arke** [comment]
I'm not sure this is much more to tell: if you use CVS then you know what it is and what this plugin will provide you. If you don't use CVS then you're highly unlikely to use this plugin in any way.

**Comment by IRobL** [comment]
Hmm... would you be able to put that into words that would help someone who's recently been assigned to maintain a Jenkins server, and sees that the plugin is checked, but does not know if it is being used?  Is there a way to test whether CVS is definitively in use?

**Comment by IRobL** [comment]
I think the reason the people haven't been able to write a meaningful explanation of the plugin because this repository doesn't have enough information in it's README file to go off of yet, so it still might be worth investigating down the road as a backlog item.  

For example, Is CVS a proprietary software application?  Maybe just a link to that would help them set things right, you know?

**Comment by oleg-nenashev** [comment]
> I think the reason the people haven't been able to write a meaningful explanation of the plugin because this repository doesn't have enough information in it's README file to go off of yet, so it still might be worth investigating down the road as a backlog item.

You are more then welcome to propose a PR with documentation update.

**Pull request merged**
